#!/bin/bash
#SBATCH --job-name=modules          # Job name
#SBATCH --ntasks=1                  # Run a single task
#SBATCH --time=00:05:00             # Time limit hrs:min:sec
#SBATCH -p EPYC
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err

module purge
echo "a) "$LD_LIBRARY_PATH
module load openMPI/4.1.5/gnu
echo "b) "$LD_LIBRARY_PATH
module purge
echo "c) "$LD_LIBRARY_PATH
module load openMPI/4.1.5/icx
echo "d) "$LD_LIBRARY_PATH
